### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by Jerrry-Li** [JiangWeibeta/MLIC#1]
作者您好，我想请教一下您文章里那么多的方法的结果都是从哪里得到的，我只能从公开的资源上获取，那些未公开的您都是邮件联系得到的吗？不知道您是否愿意将其开源。谢谢。期待您的回复

**Comment by JiangWeibeta** [comment]
你好！大部分是从公开渠道获得的(作者开源的代码或者用给出的模型进行测试)。未开源的会通过邮件向作者询问。如果作者一直不回复的话可以使用Web Plot Digitizer估计数据。Web Plot Digitizer估计出的数据一般非常接近原始数据。
