### ISSUE TITLE
README link to playground does not work

### ISSUE THREAD

**Issue by xferrari** [JiangWeibeta/MLIC#11]
Dear Author,

Your links to the playground under "Example command is provided [Here (https://github.com/JiangWeibeta/MLIC/tree/main/playground)." do not work.

That's because you have moved the scripts to MLIC++ folder in this commit: https://github.com/JiangWeibeta/MLIC/commit/51f22af6ca8af444a98a46cda849a3eeac7369af

This link should work :) https://github.com/JiangWeibeta/MLIC/tree/main/MLIC%2B%2B/playground

**Comment by JiangWeibeta** [comment]
Thank you! I have updated the link to playground.
