### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by hfwang2001** [JiangWeibeta/MLIC#12]
请问训练mlic++的时候大概需要多长时间使得模型收敛呢？
感觉在训练的时候这么多模块会一定程度上延长训练时间。

**Comment by dq0309** [comment]
请问您训练了吗，花了多少时间呀？

**Comment by JiangWeibeta** [comment]
可以参考以下log https://github.com/JiangWeibeta/MLIC/tree/main/MLIC%2B%2B/log/mlicpp_mse_0250
实际上不需要这么多步，有部分loss已经不下降了，可以提前修改patch size和learning rate

**Comment by dq0309** [comment]
> 可以参考以下log https://github.com/JiangWeibeta/MLIC/tree/main/MLIC%2B%2B/log/mlicpp_mse_0250 实际上不需要这么多步，有部分loss已经不下降了，可以提前修改patch size和learning rate

您好 请问这是从0开始训练吗

**Comment by dq0309** [comment]
> 可以参考以下log https://github.com/JiangWeibeta/MLIC/tree/main/MLIC%2B%2B/log/mlicpp_mse_0250 实际上不需要这么多步，有部分loss已经不下降了，可以提前修改patch size和learning rate

我验证和测试集的尺寸较大，是1600*1152。这样是不是test_epoch的速度会很慢，我感觉比训练cheng慢很多~

**Comment by JiangWeibeta** [comment]
> > 可以参考以下log https://github.com/JiangWeibeta/MLIC/tree/main/MLIC%2B%2B/log/mlicpp_mse_0250 实际上不需要这么多步，有部分loss已经不下降了，可以提前修改patch size和learning rate
> 
> 您好 请问这是从0开始训练吗

是的

**Comment by JiangWeibeta** [comment]
> > 可以参考以下log https://github.com/JiangWeibeta/MLIC/tree/main/MLIC%2B%2B/log/mlicpp_mse_0250 实际上不需要这么多步，有部分loss已经不下降了，可以提前修改patch size和learning rate
> 
> 我验证和测试集的尺寸较大，是1600*1152。这样是不是test_epoch的速度会很慢，我感觉比训练cheng慢很多~

如果觉得慢的话可以在前期增加每个epoch的迭代步数，减少test epoch的数目
