### ISSUE TITLE
学习率设置

### ISSUE THREAD

**Issue by YY-RR-ZZ** [JiangWeibeta/MLIC#13]
您好！非常感谢您的开源代码，这是个伟大的工作！我想请问您在不同阶段设置了不同的学习率，调低lr的同时，是否需要对aux-learning-rate辅助学习率也调小?
parser.add_argument(
        "--aux-learning-rate",
        default=1e-3,
        help="Auxiliary loss learning rate (default: %(default)s)",
    )

**Comment by JiangWeibeta** [comment]
你好，不需要对aux learning rate进行调整

**Comment by YY-RR-ZZ** [comment]
> 你好，不需要对aux learning rate进行调整

好的，谢谢.
