### ISSUE TITLE
数据集图片resize的问题

### ISSUE THREAD

**Issue by ZeonH** [JiangWeibeta/MLIC#2]
img.resize((new_width, new_height), Image.ANTIALIAS)
请问new_width和new_height是设置成多少呢？

**Comment by JiangWeibeta** [comment]
对于分辨率非常大的图，比如2k，我将它下采样到原来宽高的1/2；其他的是最短边下采样到512 or 544，最长边按短边的系数下采样以保持纵横比。

**Comment by JiangWeibeta** [comment]
需要注意的是，我给出的 train_list.txt 中有部分是重复的，COCO17和COCO14中有图片是重复的，这是我最近发现的，所以不需要包含COCO14，COCO15等数据集的图片

**Comment by ZeonH** [comment]
好的，感谢
