### ISSUE TITLE
关于Parameters(/M) FLOPs (/G)的计算

### ISSUE THREAD

**Issue by fengyurenpingsheng** [JiangWeibeta/MLIC#3]
非常感谢你提供的源代码和测试数据，我想问你一下其他论文中的参数量和FLops是怎么计算的，你有什么建议么

**Comment by JiangWeibeta** [comment]
你好，我是使用的deepspeed库计算flops，可以参考这里https://www.deepspeed.ai/tutorials/flops-profiler/。

**Comment by fengyurenpingsheng** [comment]
非常感谢
