### ISSUE TITLE
 the compared methods

### ISSUE THREAD

**Issue by xuezhongcailian** [JiangWeibeta/MLIC#5]
Hello, author. Thank you for your work. I would like to ask, in the training set you selected, to ensure fairness, do all the compared methods need to be retrained on the training set you selected?

**Comment by JiangWeibeta** [comment]
We compared directly with the official results of other models. 
The dataset does not have a significant impact on image compression as long as the amount of images is large enough. When training ELIC with our dataset, its performance is essentially indistinguishable from the official ELIC. 
Training an image compression model usually requires 2 million iterations, and retraining the model would consume a very large amount of resources. Therefore, in image compression community, researchers usually compare directly with the official results.
