### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by fapingqaz** [JiangWeibeta/MLIC#6]
ImportError: Cannot Import 'ste_round' from 'compressai.ops'.
I cannot find 'ste_round' in the GitHub Pages(https://interdigitalinc.github.io/CompressAI/).

**Comment by JiangWeibeta** [comment]
Please note that we use CompressAI 1.2.0b3. In the latest CompressAI, you need to import quantize_ste.

**Comment by BearCooike** [comment]
更新一下，现在叫 quantize_ste
