### ISSUE TITLE
Checkpoints update

### ISSUE THREAD

**Issue by michaldyczko** [JiangWeibeta/MLIC#8]
> Update 2024-04-08
> I upload the training log when the lambda is 0.0250. The model is trained on 4 GPU cards with ddp support.
> 
> I fix the LatentResidualPrediction and SynthesisTransform, you should use LatentResidualPredictionFix and SynthesisTransformFix. The parameter number becomes 83.5M. The modification leads to no performance drop.

It would be great if you share pretrained models after this update.

**Comment by JiangWeibeta** [comment]
I only trained model optimized for MSE and the lambda is 0.025.
You can download the checkpoints at https://disk.pku.edu.cn/link/AABED8912D2502477EB37C18FC7F2B2612
code: ujrv

**Comment by michaldyczko** [comment]
@JiangWeibeta, the download speed from PKU is painfully small for me (~20kB/s). Could you upload it on Google Disk also? Thank you in advance!

**Comment by JiangWeibeta** [comment]
You can download the checkpoint on Google drive now. Here's the url
https://drive.google.com/file/d/1FWPezuHLTQhDmEhShViI3XOSXA5u_Bya/view?usp=sharing

**Comment by michaldyczko** [comment]
Thank you so much!
