### ISSUE TITLE
作者您好，请问一下您在训练模型过程中有遇到过张量不匹配问题吗

### ISSUE THREAD

**Issue by kongcheng-996** [JiangWeibeta/MLIC#9]
![Screenshot 2024-05-15 020116](https://github.com/JiangWeibeta/MLIC/assets/89571216/0c31d129-3147-4bc8-a7d9-0376e8e6f1b7)

**Comment by kongcheng-996** [comment]
图片大小是788 2048，patch_size是256 256

**Comment by JiangWeibeta** [comment]
我猜是因为test_one_epoch不匹配，test epoch时没有取patch，输入分辨率应为64的倍数，你可以裁剪或者pad 0

**Comment by kongcheng-996** [comment]
是这样的，需要对测试集进行裁剪，谢谢。
